exclude_keywords:
- Marketing
- Sales
- Graphic Design
- Content Reviewer
- Product Manager
- HR
- Recruiter
- Customer Support
- Call Center
min_match_score: 70
preferred_job_types:
- Full-time
- Internship
- Remote
- Contract
preferred_locations:
- Hyderabad
- Bangalore
- Bengaluru
- Andhra Pradesh
- Visakhapatnam
- Chennai
- Pune
- Remote
- Hybrid
- India
- Worldwide
- Anywhere
- Work from Home
target_titles:
- Python Developer
- Machine Learning Engineer
- Data Analyst
- AI Engineer
- Software Engineer
- Backend Developer
- Full Stack Developer
- Python Intern
- Data Science Intern
- Junior Software Engineer
